name: CI
on: pull_request
env:
  BUILD_ENV: production
  IMGIX_API_KEY: ${{ secrets.IMGIX_API_KEY }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Yarn Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Run Linter
        run: yarn lint
      - name: Deploy to Netlify
        run: |
          ./packages/website/node_modules/.bin/netlify deploy --json > a.json
          # Parse deployment URL
          DEPLOY_URL=$(echo "console.log(require('./a.json').deploy_url)" | node)
          echo "::set-env name=DEPLOY_URL::$DEPLOY_URL"
      - uses: cornell-dti/dti-repo-tools@master
        env:
          BOT_TOKEN: '${{ secrets.BOT_TOKEN }}'
        with:
          command: pr-comment
          argument: '[deployment-bot] Deployed to ${{env.DEPLOY_URL}}.'
