name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Yarn Install
        run: yarn install
      - name: Build JSON
        run: node cli.js
      - name: Run Linter
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Upload Built Static Assets
        uses: actions/upload-artifact@master
        with:
          name: built-assets
          path: dist
